CREATE TABLE DOCENTE (
    ID_DOCENTE INT NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR(100),
    APELLIDO_MAT VARCHAR(60),
    APELLIDO_PAT VARCHAR(60),
    CAMPUS VARCHAR(50),
	VIGENCIA INT CONSTRAINT DF_DOCENTE_VIGENTE DEFAULT (1),
	CONTRA VARCHAR(20),
	CORREO VARCHAR(50),
    TELEFONO VARCHAR(15),
    CONSTRAINT PK_DOCENTE PRIMARY KEY (ID_DOCENTE),
    CONSTRAINT CHK_DOCENTE_VIGENTE CHECK (VIGENCIA IN (0,1))
);

CREATE TABLE JEFE (
    JEFE_ID INT NOT NULL,
    NOMBRE VARCHAR(100),
    VIGENTE BIT CONSTRAINT DF_JEFE_VIGENTE DEFAULT (1),
	CONTRA VARCHAR(20),
	CORREO VARCHAR(50),
    CONSTRAINT PK_JEFE PRIMARY KEY (JEFE_ID),
    CONSTRAINT CHK_JEFE_VIGENTE CHECK (VIGENTE IN (0,1))
);

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT NOT NULL,
    JEFE_ID INT,
	NOMBRE VARCHAR(50),
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID_DEPARTAMENTO),
    CONSTRAINT FK_DEP_JEFE_ID FOREIGN KEY (JEFE_ID) REFERENCES JEFE(JEFE_ID)
);

CREATE TABLE CONVOCATORIA (
    ID_CONVOCATORIA INT NOT NULL,
    NOMBRE VARCHAR(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    CONSTRAINT PK_CONVOCATORIA PRIMARY KEY (ID_CONVOCATORIA)
);

CREATE TABLE EXPEDIENTE (
    ID_EXPEDIENTE INT NOT NULL,
    ID_DOCENTE INT,
    ID_CONVOC INT,
    CONSTRAINT PK_EXPEDIENTE PRIMARY KEY (ID_EXPEDIENTE),
    CONSTRAINT FK_EXPEDIENTE_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
    CONSTRAINT FK_EXPEDIENTE_CONVOC FOREIGN KEY (ID_CONVOC) REFERENCES CONVOCATORIA(ID_CONVOCATORIA)
);

CREATE TABLE DOCUMENTO (
    FOLIO INT NOT NULL IDENTITY(1,1),
    ID_DEPARTAMENTO INT,
	NOMBRE VARCHAR(50),
    FECHA DATE,
    CONSTRAINT PK_DOCUMENTO PRIMARY KEY (FOLIO),
    CONSTRAINT FK_DOCUMENTO_DEP FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CONSTRAINT CHK_DOCUMENTO_APROBACION CHECK (APROBACION IN (0,1))
);

CREATE TABLE DOCUMENTO_EXPEDIENTE (
    ID_DOCUMENTO INT NOT NULL,
    ID_EXPEDIENTE INT NOT NULL,
    CONSTRAINT PK_DOCUMENTO_EXPEDIENTE PRIMARY KEY (ID_DOCUMENTO, ID_EXPEDIENTE),
    CONSTRAINT FK_DOC_EXP_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(FOLIO),
    CONSTRAINT FK_DOC_EXP_EXPEDIENTE FOREIGN KEY (ID_EXPEDIENTE) REFERENCES EXPEDIENTE(ID_EXPEDIENTE)
);

CREATE TABLE RECLAMO (
    ID_RECLAMO INT NOT NULL IDENTITY(1,1),
    ID_DOCUMENTO INT,
    FECHA DATE,
    CONSTRAINT PK_RECLAMO PRIMARY KEY (ID_RECLAMO),
    CONSTRAINT FK_RECLAMO_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(FOLIO)
);

CREATE TABLE COMENTARIOS (
    ID_COMENTARIO INT IDENTITY(1,1) NOT NULL,
	ID_RECLAMO INT NOT NULL,
    REMITENTE VARCHAR(10),
    FECHA DATETIME,
    DESCRIPCION VARCHAR(255),
    CONSTRAINT PK_COMENTARIOS PRIMARY KEY (ID_COMENTARIO),
    CONSTRAINT FK_COMENTARIOS_RECLAMO FOREIGN KEY (ID_RECLAMO) REFERENCES RECLAMO(ID_RECLAMO)
);
-- ======================
-- INSERTS DE EJEMPLO
-- ======================
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Formato-para-el-Horario-de-Actividades', GETDATE());

INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia-De-Tutoria', GETDATE());

INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Consejo_Nacional_de_Acreditación', GETDATE());

INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'CONSTANCIA', GETDATE());


INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'COMISIÓN DE EVALUACIÓN DEL PROGRAMA DE ESTÍMULOS AL DESEMPEÑO DEL PERSONAL DOCENTE', GETDATE());

INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia de Trabajo', GETDATE());

INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'COMISIÓN DE EVALUACIÓN DEL PROGRAMA DE ESTÍMULOS AL DESEMPEÑO DEL PERSONAL DOCENTE', GETDATE());

INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia de Productos Obtenidos y su Impacto', GETDATE());


INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'OFICIO_COMISION', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'OFICIO_COMISION', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'OFICIO_COMISION', GETDATE());

INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'CONSTANCIA_DDIE', GETDATE());

INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'OFICIO_COMISION', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'OFICIO_COMISION', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'OFICIO_COMISION', GETDATE());


INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia De Exencion De Examen Licenciatura', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia De Exencion De Examen Especializacion', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia De Exencion De Examen Maestria', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia De Exencion De Examen Maestria Codirector', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia De Exencion De Examen Doctorado', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia De Exencion De Examen Doctorado Codirector', GETDATE());


INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia SINODAL Licenciatura', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia SINODAL Especializacion', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia SINODAL Maestria', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia SINODAL Doctorado', GETDATE());


INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'CONSTANCIA_CUMPLIMIENTO', GETDATE());


INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'CONSTANCIA DE PARTICIPACIÓN', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'CERTIFICACIÓN DE EXAMEN DE GRADO', GETDATE());


INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'CARTA DE EXCLUSIVIDAD LABORAL DOCENTES CON PLAZA DE TIEMPO COMPLETO', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'H. COMISION DICTAMINADORA DEL EDD PRESENTE', GETDATE());


INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia de Participación y Trabajo Terminado', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Autorización de Apertura de Programa de Estudio', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Constancia de Participación', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Comisión para Diseño de Módulos de Especialidad', GETDATE());
INSERT INTO Documento (ID_DEPARTAMENTO, Nombre, FECHA)
VALUES (10, 'Registro de Módulos de Especialidad', GETDATE());


-- JEFE
INSERT INTO JEFE (JEFE_ID, NOMBRE, VIGENTE, CONTRA, CORREO)
VALUES (1000, 'Carlos Gómez', 1, 'abcd', 'carlos@eddo.mx');

-- DOCENTE
INSERT INTO DOCENTE (NOMBRE, VIGENCIA, CONTRA, CORREO, TELEFONO)
VALUES ('Ana Torres', 1, '123', 'ana.torres@tecnm.mx', '6671234567');

-- DEPARTAMENTO
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, JEFE_ID, NOMBRE)
VALUES (10, 1000, 'Ingeniería en Sistemas Computacionales');

-- CONVOCATORIA
INSERT INTO CONVOCATORIA (ID_CONVOCATORIA, NOMBRE, FECHA_INICIO, FECHA_FIN)
VALUES (200, 'Convocatoria 2025A', '2025-01-10', '2025-06-30');

-- EXPEDIENTE
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_DOCENTE, ID_CONVOC)
VALUES (300, 1, 200);


-- DOCUMENTO_EXPEDIENTE (relación muchos a muchos)
INSERT INTO DOCUMENTO_EXPEDIENTE (ID_DOCUMENTO, ID_EXPEDIENTE)
VALUES 
(1, 300),
(2, 300);

-- RECLAMO
INSERT INTO RECLAMO (ID_RECLAMO, ID_DOCUMENTO, FECHA)
VALUES 
(700, 1, '2025-04-12');

-- COMENTARIOS
INSERT INTO COMENTARIOS (ID_RECLAMO, REMITENTE, FECHA, DESCRIPCION)
VALUES 
(700, 'DOCENTE', GETDATE(), 'El documento fue rechazado por error en formato.'),
(700, 'JEFE', GETDATE(), 'Favor de corregir el formato del archivo PDF.');

SELECT 
    DOC.NOMBRE AS NOMBRE_DOCUMENTO,
    DOC.APROBACION,
    DOC.FOLIO
FROM DOCUMENTO DOC
JOIN DOCUMENTO_EXPEDIENTE DE ON DOC.FOLIO = DE.ID_DOCUMENTO
JOIN EXPEDIENTE E ON DE.ID_EXPEDIENTE = E.ID_EXPEDIENTE
JOIN DOCENTE D ON E.ID_DOCENTE = D.ID_DOCENTE
JOIN CONVOCATORIA C ON E.ID_CONVOC = C.ID_CONVOCATORIA
JOIN DEPARTAMENTO DEP ON DOC.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
JOIN JEFE J ON DEP.JEFE_ID = J.JEFE_ID
JOIN TIPO_DOCUMENTO TD ON DOC.ID_TIPO_DOCUMENTO = TD.ID_TIPO_DOCUMENTO
JOIN RECLAMO R ON DOC.FOLIO = R.ID_DOCUMENTO
where D.ID_DOCENTE = 1

SELECT 
    DOC.NOMBRE AS NOMBRE_DOCUMENTO,
    DOC.APROBACION,
    DOC.FOLIO,
    CO.DESCRIPCION
FROM DOCUMENTO DOC
JOIN DOCUMENTO_EXPEDIENTE DE ON DOC.FOLIO = DE.ID_DOCUMENTO
JOIN EXPEDIENTE E ON DE.ID_EXPEDIENTE = E.ID_EXPEDIENTE
JOIN DOCENTE D ON E.ID_DOCENTE = D.ID_DOCENTE
JOIN CONVOCATORIA C ON E.ID_CONVOC = C.ID_CONVOCATORIA
JOIN DEPARTAMENTO DEP ON DOC.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
JOIN JEFE J ON DEP.JEFE_ID = J.JEFE_ID
JOIN TIPO_DOCUMENTO TD ON DOC.ID_TIPO_DOCUMENTO = TD.ID_TIPO_DOCUMENTO
JOIN RECLAMO R ON DOC.FOLIO = R.ID_DOCUMENTO
JOIN COMENTARIOS CO ON CO.ID_RECLAMO = R.ID_RECLAMO
WHERE (D.ID_DOCENTE = 1 AND DOC.NOMBRE like 'Reconocimiento de Proyecto IA') OR (J.JEFE_ID = 1 and  DOC.NOMBRE like 'Reconocimiento de Proyecto IA')
            
            SELECT 
                doc.NOMBRE,
                CO.remitente,
                CO.fecha,
                CO.descripcion,
                d.ID_DOCENTE,
                R.ID_RECLAMO
            FROM DOCUMENTO DOC
            JOIN DOCUMENTO_EXPEDIENTE DE ON DOC.FOLIO = DE.ID_DOCUMENTO
            JOIN EXPEDIENTE E ON DE.ID_EXPEDIENTE = E.ID_EXPEDIENTE
            JOIN DOCENTE D ON E.ID_DOCENTE = D.ID_DOCENTE
            JOIN CONVOCATORIA C ON E.ID_CONVOC = C.ID_CONVOCATORIA
            JOIN DEPARTAMENTO DEP ON DOC.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
            JOIN JEFE J ON DEP.JEFE_ID = J.JEFE_ID
            JOIN TIPO_DOCUMENTO TD ON DOC.ID_TIPO_DOCUMENTO = TD.ID_TIPO_DOCUMENTO
            JOIN RECLAMO R ON DOC.FOLIO = R.ID_DOCUMENTO
            JOIN COMENTARIOS CO ON CO.ID_RECLAMO = R.ID_RECLAMO
            WHERE (D.ID_DOCENTE = 1 AND R.id_Reclamo = 700)

            SELECT 
                R.id_reclamo,
                DOC.NOMBRE AS nombre_documento,
                DOC.folio,
                R.fecha
            FROM DOCUMENTO DOC
            JOIN DOCUMENTO_EXPEDIENTE DE ON DOC.FOLIO = DE.ID_DOCUMENTO
            JOIN EXPEDIENTE E ON DE.ID_EXPEDIENTE = E.ID_EXPEDIENTE
            JOIN DOCENTE D ON E.ID_DOCENTE = D.ID_DOCENTE
            JOIN CONVOCATORIA C ON E.ID_CONVOC = C.ID_CONVOCATORIA
            JOIN DEPARTAMENTO DEP ON DOC.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
            JOIN JEFE J ON DEP.JEFE_ID = J.JEFE_ID
            JOIN TIPO_DOCUMENTO TD ON DOC.ID_TIPO_DOCUMENTO = TD.ID_TIPO_DOCUMENTO
            JOIN RECLAMO R ON DOC.FOLIO = R.ID_DOCUMENTO
            where D.ID_DOCENTE = 1000 or J.JEFE_ID = 1000
SELECT 
    C.REMITENTE,
    C.FECHA AS FECHA_COMENTARIO,
    C.DESCRIPCION
FROM COMENTARIOS C
JOIN RECLAMO R ON C.ID_RECLAMO = R.ID_RECLAMO
JOIN DOCUMENTO D ON R.ID_DOCUMENTO = D.FOLIO
JOIN EXPEDIENTE E ON D.ID_EXPEDIENTE = E.ID_EXPEDIENTE
JOIN DOCENTE DOC ON E.ID_DOCENTE = DOC.ID_DOCENTE
JOIN DEPARTAMENTO DEP ON D.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
JOIN JEFE J ON DEP.JEFE_ID = J.JEFE_ID
WHERE (DOC.ID_DOCENTE = 1 AND DOC.NOMBRE = 501) OR (J.JEFE_ID = 1 and  DOC.NOMBRE = 501)
            SELECT * FROM RECLAMO
-- CHECKS Y DEFAULTS (ejemplo base, puedes ampliar)
ALTER TABLE DOCENTE ADD CONSTRAINT CHK_DOCENTE_VIGENTE CHECK (VIGENCIA IN (0,1));
ALTER TABLE JEFE ADD CONSTRAINT CHK_JEFE_VIGENTE CHECK (VIGENTE IN (0,1));
ALTER TABLE DOCUMENTO ADD CONSTRAINT CHK_DOCUMENTO_APROBACION CHECK (APROBACION IN (0,1));

ALTER TABLE DOCENTE ADD CONSTRAINT DF_DOCENTE_VIGENTE DEFAULT (1) FOR VIGENCIA;
ALTER TABLE JEFE ADD CONSTRAINT DF_JEFE_VIGENTE DEFAULT (1) FOR VIGENTE;
ALTER TABLE DOCUMENTO ADD CONSTRAINT DF_DOCUMENTO_APROBACION DEFAULT (0) FOR APROBACION;
