--vw_DocenteConvocatoriaExpediente

--vw_ComentariosReclamo

--vw_TipoActividad

--vw_JefeDepartamento

--vw_Documento


CREATE OR ALTER VIEW vw_DocenteConvocatoriaExpediente
AS
SELECT 
    D.ID_DOCENTE,
    D.NOMBRE AS NOMBRE_DOCENTE,
    D.CORREO,
    D.VIGENCIA,
    D.TELEFONO,
    C.ID_CONVOCATORIA,
    C.NOMBRE AS NOMBRE_CONVOCATORIA,
    C.FECHA_INICIO,
    C.FECHA_FIN,
    E.ID_EXPEDIENTE
FROM EXPEDIENTE E
INNER JOIN DOCENTE D ON E.ID_DOCENTE = D.ID_DOCENTE
INNER JOIN CONVOCATORIA C ON E.ID_CONVOC = C.ID_CONVOCATORIA;
GO

CREATE VIEW vw_ComentariosReclamo
AS
SELECT 
    C.ID_COMENTARIO,
    C.DESCRIPCION AS COMENTARIO,
    R.ID_RECLAMO,
    R.ID_DOCUMENTO,
    R.FECHA AS FECHA_RECLAMO
FROM COMENTARIOS C
INNER JOIN RECLAMO R ON C.ID_RECLAMO = R.ID_RECLAMO;
GO

CREATE VIEW vw_TipoActividad
AS
SELECT 
    A.ID_ACTIVIDAD,
    A.NOMBRE AS NOMBRE_ACTIVIDAD,
    A.DESCRIPCION,
    T.ID_TIPO_ACTIVIDAD,
    T.NOMBRE AS NOMBRE_TIPO_ACTIVIDAD
FROM ACTIVIDAD A
INNER JOIN TIPO_ACTIVIDAD T 
    ON A.ID_TIPO_ACTIVIDAD = T.ID_TIPO_ACTIVIDAD;
GO

CREATE VIEW vw_JefeDepartamento
AS
SELECT 
    D.ID_DEPARTAMENTO,
    D.NOMBRE AS NOMBRE_DEPARTAMENTO,
    J.JEFE_ID,
    J.NOMBRE AS NOMBRE_JEFE,
    J.CORREO AS CORREO_JEFE,
    J.VIGENTE AS JEFE_VIGENTE
FROM DEPARTAMENTO D
INNER JOIN JEFE J 
    ON D.JEFE_ID = J.JEFE_ID;
GO

CREATE OR ALTER VIEW vw_Documento
AS
SELECT 
    DCE.ID_DOCENTE,
    DCE.NOMBRE_DOCENTE,
    DCE.CORREO,
    DCE.ID_EXPEDIENTE,
    DCE.ID_CONVOCATORIA,
    DCE.NOMBRE_CONVOCATORIA,
    DCE.FECHA_INICIO,
    DCE.FECHA_FIN,
    DCE.TELEFONO,

    DOC.FOLIO AS FOLIO_DOCUMENTO,
    TD.NOMBRE_DOCUMENTO,
    DOC.APROBACION,
    DOC.FECHA AS FECHA_DOCUMENTO,

    ATA.ID_ACTIVIDAD,
    ATA.NOMBRE_ACTIVIDAD,
    ATA.DESCRIPCION AS DESCRIPCION_ACTIVIDAD,
    ATA.NOMBRE_TIPO_ACTIVIDAD,

    JD.ID_DEPARTAMENTO,
    JD.NOMBRE_DEPARTAMENTO,
    JD.NOMBRE_JEFE,
    JD.CORREO_JEFE,

    CR.ID_RECLAMO,
    CR.FECHA_RECLAMO,
    CR.ID_COMENTARIO,
    CR.COMENTARIO

FROM DOCUMENTO DOC
INNER JOIN TIPO_DOCUMENTO TD 
    ON DOC.ID_TIPO_DOCUMENTO = TD.ID_TIPO_DOCUMENTO

INNER JOIN vw_DocenteConvocatoriaExpediente DCE 
    ON DOC.ID_EXPED = DCE.ID_EXPEDIENTE

INNER JOIN vw_TipoActividad ATA 
    ON DOC.ID_ACTIVIDAD = ATA.ID_ACTIVIDAD

INNER JOIN vw_JefeDepartamento JD 
    ON DOC.ID_DEPARTAMENTO = JD.ID_DEPARTAMENTO

LEFT JOIN vw_ComentariosReclamo CR 
    ON DOC.FOLIO = CR.ID_DOCUMENTO;
GO

SELECT * FROM vw_Documento