INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (1, 'CONSTANCIA DE TUTORÍA');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (2, 'Consejo Nacional de Acreditación');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (3, 'CONSTANCIA');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (4, 'COMISIÓN DE EVALUACIÓN DEL PROGRAMA DE ESTÍMULOS');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (5, 'COMISIÓN DE EVALUACIÓN DEL PROGRAMA DE ESTÍMULOS (HABILIDADES)');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (6, 'CONSTANCIA DE EXTENSIÓN DE EXAMEN PROFESIONAL');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (7, 'CONSTANCIA DE PARTICIPACIÓN');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (8, 'CERTIFICACIÓN DE EXAMEN DE GRADO');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (9, 'CARTA DE EXCLUSIVIDAD LABORAL');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (10, 'H. COMISIÓN DICTAMINADORA DEL EDD');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (11, 'Constancia de Participación y Trabajo Terminado');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (12, 'Autorización de Apertura de Programa de Estudio');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (13, 'Constancia de Participación');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (14, 'Comisión para Diseño de Módulos de Especialidad');
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE) VALUES (15, 'Registro de Módulos de Especialidad');


