CREATE database BDEDD;
-- ================================
-- TABLA: REQUISITOS_DE_INICIO
-- ================================
CREATE TABLE REQUISITOS_DE_INICIO (
    ID_REQUISITO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(300)
);

-- ================================
-- TABLA: CONVOCATORIA
-- ================================
CREATE TABLE CONVOCATORIA (
    ID_CONVOCATORIA INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL
);

-- ================================
-- TABLA: DOCENTE
-- ================================
CREATE TABLE DOCENTE (
    ID_DOCENTE INT NOT NULL IDENTITY,
    NOMBRE VARCHAR(100),
    APELLIDO_PAT VARCHAR(60),
    APELLIDO_MAT VARCHAR(60),
    CAMPUS VARCHAR(50),
	VIGENCIA INT CONSTRAINT DF_DOCENTE_VIGENTE DEFAULT (1),
	CONTRA VARCHAR(20),
	CORREO VARCHAR(50),
    TELEFONO VARCHAR(15),
    CONSTRAINT CHK_DOCENTE_VIGENTE CHECK (VIGENCIA IN (0,1))
);

-- ================================
-- TABLA: REQUISITO_CONVO
-- Relaciona requisitos ↔ convocatorias (N:M)
-- ================================
CREATE TABLE REQUISITO_CONVO (
    ID_REQUISITO INT NOT NULL,
    ID_CONVOCATORIA INT NOT NULL
);

-- ================================
-- TABLA: DOCENTE_REQUISITOS
-- Docente entrega requisito por convocatoria
-- ================================
CREATE TABLE DOCENTE_REQUISITOS (
    ID_DOCENTE INT NOT NULL,
    ID_REQUISITO INT NOT NULL,
    ID_CONVOCATORIA INT NOT NULL,
    DOCUMENTO_RUTA VARCHAR(300) NOT NULL
);
ALTER TABLE REQUISITOS_DE_INICIO
ADD CONSTRAINT PK_REQUISITOS_DE_INICIO
PRIMARY KEY (ID_REQUISITO);

ALTER TABLE CONVOCATORIA
ADD CONSTRAINT PK_CONVOCATORIA
PRIMARY KEY (ID_CONVOCATORIA);

ALTER TABLE DOCENTE
ADD CONSTRAINT PK_DOCENTE
PRIMARY KEY (ID_DOCENTE);

ALTER TABLE REQUISITO_CONVO
ADD CONSTRAINT PK_REQUISITO_CONVO
PRIMARY KEY (ID_REQUISITO, ID_CONVOCATORIA);

ALTER TABLE DOCENTE_REQUISITOS
ADD CONSTRAINT PK_DOCENTE_REQUISITOS
PRIMARY KEY (ID_DOCENTE, ID_REQUISITO, ID_CONVOCATORIA);

-- REQUISITO_CONVO → REQUISITOS_DE_INICIO
ALTER TABLE REQUISITO_CONVO
ADD CONSTRAINT FK_REQUISITOCONVO_REQUISITO
FOREIGN KEY (ID_REQUISITO)
REFERENCES REQUISITOS_DE_INICIO(ID_REQUISITO);

-- REQUISITO_CONVO → CONVOCATORIA
ALTER TABLE REQUISITO_CONVO
ADD CONSTRAINT FK_REQUISITOCONVO_CONVOCATORIA
FOREIGN KEY (ID_CONVOCATORIA)
REFERENCES CONVOCATORIA(ID_CONVOCATORIA);

-- DOCENTE_REQUISITOS → DOCENTE
ALTER TABLE DOCENTE_REQUISITOS
ADD CONSTRAINT FK_DOCR_DOCENTE
FOREIGN KEY (ID_DOCENTE)
REFERENCES DOCENTE(ID_DOCENTE);

-- DOCENTE_REQUISITOS → REQUISITOS_DE_INICIO
ALTER TABLE DOCENTE_REQUISITOS
ADD CONSTRAINT FK_DOCR_REQUISITO
FOREIGN KEY (ID_REQUISITO)
REFERENCES REQUISITOS_DE_INICIO(ID_REQUISITO);

-- DOCENTE_REQUISITOS → CONVOCATORIA
ALTER TABLE DOCENTE_REQUISITOS
ADD CONSTRAINT FK_DOCR_CONVOCATORIA
FOREIGN KEY (ID_CONVOCATORIA)
REFERENCES CONVOCATORIA(ID_CONVOCATORIA);
