-- 1. CREAR LA BASE DE DATOS
CREATE DATABASE EDDO
USE EDDO

-- 2. CREAR TABLAS SIN DEPENDENCIAS EXTERNAS (PADRES)

CREATE TABLE DOCENTE (
    ID_DOCENTE INT NOT NULL PRIMARY KEY,
    CAMPUS VARCHAR(25),
    NOMBRES VARCHAR(15),
    APELLIDO_PAT VARCHAR(15),
    APELLIDO_MAT VARCHAR(15),
    ORGANIZ_REQUI_INICO VARCHAR(100),
    CORREO VARCHAR(100),
    CONTRASEÑA VARCHAR(255)
)

CREATE TABLE CONVOCATORIA (
    ID_CONVOCATORIA INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(255),
    FECHA_INICIO DATE,
    FECHA_FIN DATE
)

CREATE TABLE JEFE (
    ID_DOCENTE INT NOT NULL,
    FIRMA_TOKEN_JEFE VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255),
    CORREO VARCHAR(255),
    CONTRASEÑA VARCHAR(255),
    PRIMARY KEY (ID_DOCENTE, FIRMA_TOKEN_JEFE)
)

CREATE TABLE Tipo_Actividad (
    ID_TIPO_ACTIVIDAD INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(255)
)

CREATE TABLE Tipo_Documento (
    ID_TIPO_DOCUMENTO INT NOT NULL PRIMARY KEY,
    NOMBRE_DOCUMENTO VARCHAR(255)
)

-- 3. CREAR TABLAS CON DEPENDENCIAS (HIJOS)

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT NOT NULL PRIMARY KEY,
    ID_TIPO_DEP INT NOT NULL,
    ID_JEFE INT NOT NULL,
    FIRMA_TOKEN_JEFE VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_JEFE, FIRMA_TOKEN_JEFE) REFERENCES JEFE(ID_DOCENTE, FIRMA_TOKEN_JEFE)
)

CREATE TABLE EXPEDIENTE (
    ID_EXPEDIENTE INT NOT NULL PRIMARY KEY,
    ID_DOCENTE INT NOT NULL,
    FK_ID_CONVOC INT NOT NULL,
    FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
    FOREIGN KEY (FK_ID_CONVOC) REFERENCES CONVOCATORIA(ID_CONVOCATORIA)
)

CREATE TABLE Actividad (
    ID_ACTIVIDAD INT NOT NULL PRIMARY KEY,
    ID_TIPO_ACTIVIDAD INT NOT NULL, -- Columna añadida para la FK
    DESCRIPCION TEXT,
    PUNTOS DECIMAL(5, 2),
    FOREIGN KEY (ID_TIPO_ACTIVIDAD) REFERENCES Tipo_Actividad(ID_TIPO_ACTIVIDAD)
)

CREATE TABLE DOCUMENTO (
    FOLIO INT NOT NULL PRIMARY KEY,
    ID_DOCENTE INT NOT NULL,
    ID_JEFE INT NOT NULL,
    ID_TIPO_DOCUMENTO INT NOT NULL,
    ID_EXPEDIENTE INT NOT NULL,
    ID_DEPARTAMENTO INT NOT NULL,
    ID_ACTIVIDAD INT NOT NULL,
    FIRMA_TOKEN_JEFE VARCHAR(255) NOT NULL,
    APROBACION CHAR(15),
    FECHA DATE,
    FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
    FOREIGN KEY (ID_JEFE, FIRMA_TOKEN_JEFE) REFERENCES JEFE(ID_DOCENTE, FIRMA_TOKEN_JEFE),
    FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES Tipo_Documento(ID_TIPO_DOCUMENTO),
    FOREIGN KEY (ID_EXPEDIENTE) REFERENCES EXPEDIENTE(ID_EXPEDIENTE),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    FOREIGN KEY (ID_ACTIVIDAD) REFERENCES Actividad(ID_ACTIVIDAD)
)

CREATE TABLE RECLAMO (
    ID_RECLAMO INT NOT NULL PRIMARY KEY,
    ID_DOCENTE INT NOT NULL,
    ID_JEFE INT NOT NULL,
    ID_DOCUMENTO INT NOT NULL, -- Asumiendo que es el FOLIO del documento
    FECHA_INICIO DATE,
    ESTATUS ENUM('Sin Resolver', 'Resuelto'), -- Interpretando "Sin Resol/Resue"
    FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
    FOREIGN KEY (ID_JEFE) REFERENCES JEFE(ID_DOCENTE), -- FK a la parte ID_DOCENTE de la PK de JEFE
    FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(FOLIO) -- FK al FOLIO del DOCUMENTO
)

CREATE TABLE Comentarios (
    ID_COMENTARIO INT NOT NULL PRIMARY KEY,
    ID_RECLAMO INT NOT NULL,
    REMITENTE_ID_DOCE INT NULL, -- Permite NULOS como indica el diagrama (ID_DOCE/NULL)
    REMITENTE_ID_JEFE INT NULL, -- Permite NULOS como indica el diagrama (ID_JEFE/NULL)
    DESCRIPCION TEXT,
    FOREIGN KEY (ID_RECLAMO) REFERENCES RECLAMO(ID_RECLAMO),
    FOREIGN KEY (REMITENTE_ID_DOCE) REFERENCES DOCENTE(ID_DOCENTE),
    FOREIGN KEY (REMITENTE_ID_JEFE) REFERENCES JEFE(ID_DOCENTE) -- FK a la parte ID_DOCENTE de la PK de JEFE
)
