ATabase eddo
CREATE TABLE DOCENTE (
    ID_DOCENTE INT NOT NULL,
    NOMBRE VARCHAR(100),
	VIGENCIA INT CONSTRAINT DF_DOCENTE_VIGENTE DEFAULT (1),
	CONTRA VARCHAR(20),
	CORREO VARCHAR(50),
    TELEFONO VARCHAR(15),
    CONSTRAINT PK_DOCENTE PRIMARY KEY (ID_DOCENTE),
    CONSTRAINT CHK_DOCENTE_VIGENTE CHECK (VIGENCIA IN (0,1))
);

CREATE TABLE JEFE (
    JEFE_ID INT NOT NULL,
    NOMBRE VARCHAR(100),
    VIGENTE BIT CONSTRAINT DF_JEFE_VIGENTE DEFAULT (1),
	CONTRA VARCHAR(20),
	CORREO VARCHAR(50),
    CONSTRAINT PK_JEFE PRIMARY KEY (JEFE_ID),
    CONSTRAINT CHK_JEFE_VIGENTE CHECK (VIGENTE IN (0,1))
);

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT NOT NULL,
    JEFE_ID INT,
	NOMBRE VARCHAR(50),
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID_DEPARTAMENTO),
    CONSTRAINT FK_DEP_JEFE_ID FOREIGN KEY (JEFE_ID) REFERENCES JEFE(JEFE_ID)
);

CREATE TABLE CONVOCATORIA (
    ID_CONVOCATORIA INT NOT NULL,
    NOMBRE VARCHAR(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    CONSTRAINT PK_CONVOCATORIA PRIMARY KEY (ID_CONVOCATORIA)
);

CREATE TABLE EXPEDIENTE (
    ID_EXPEDIENTE INT NOT NULL,
    ID_DOCENTE INT,
    ID_CONVOC INT,
    CONSTRAINT PK_EXPEDIENTE PRIMARY KEY (ID_EXPEDIENTE),
    CONSTRAINT FK_EXPEDIENTE_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
    CONSTRAINT FK_EXPEDIENTE_CONVOC FOREIGN KEY (ID_CONVOC) REFERENCES CONVOCATORIA(ID_CONVOCATORIA)
);

CREATE TABLE TIPO_DOCUMENTO (
    ID_TIPO_DOCUMENTO INT NOT NULL,
    NOMBRE_DOCUMENTO VARCHAR(100),
    CONSTRAINT PK_TIPO_DOCUMENTO PRIMARY KEY (ID_TIPO_DOCUMENTO)
);

CREATE TABLE TIPO_ACTIVIDAD (
    ID_TIPO_ACTIVIDAD INT NOT NULL,
    NOMBRE VARCHAR(100),
    CONSTRAINT PK_TIPO_ACTIVIDAD PRIMARY KEY (ID_TIPO_ACTIVIDAD)
);

CREATE TABLE ACTIVIDAD (
    ID_ACTIVIDAD INT NOT NULL,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(255),
    ID_TIPO_ACTIVIDAD INT,
    CONSTRAINT PK_ACTIVIDAD PRIMARY KEY (ID_ACTIVIDAD),
    CONSTRAINT FK_ACTIVIDAD_TIPO_ACT FOREIGN KEY (ID_TIPO_ACTIVIDAD) REFERENCES TIPO_ACTIVIDAD(ID_TIPO_ACTIVIDAD)
);

CREATE TABLE DOCUMENTO (
    FOLIO INT NOT NULL,
    ID_TIPO_DOCUMENTO INT,
    ID_DEPARTAMENTO INT,
    ID_ACTIVIDAD INT,
	NOMBRE VARCHAR(50),
    APROBACION BIT CONSTRAINT DF_DOCUMENTO_APROBACION DEFAULT (0),
    FECHA DATE,
    CONSTRAINT PK_DOCUMENTO PRIMARY KEY (FOLIO),
    CONSTRAINT FK_DOCUMENTO_TIPO_DOC FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO),
    CONSTRAINT FK_DOCUMENTO_DEP FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CONSTRAINT FK_DOCUMENTO_ACT FOREIGN KEY (ID_ACTIVIDAD) REFERENCES ACTIVIDAD(ID_ACTIVIDAD),
    CONSTRAINT CHK_DOCUMENTO_APROBACION CHECK (APROBACION IN (0,1))
);

CREATE TABLE DOCUMENTO_EXPEDIENTE (
    ID_DOCUMENTO INT NOT NULL,
    ID_EXPEDIENTE INT NOT NULL,
    CONSTRAINT PK_DOCUMENTO_EXPEDIENTE PRIMARY KEY (ID_DOCUMENTO, ID_EXPEDIENTE),
    CONSTRAINT FK_DOC_EXP_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(FOLIO),
    CONSTRAINT FK_DOC_EXP_EXPEDIENTE FOREIGN KEY (ID_EXPEDIENTE) REFERENCES EXPEDIENTE(ID_EXPEDIENTE)
);

CREATE TABLE RECLAMO (
    ID_RECLAMO INT NOT NULL,
    ID_DOCUMENTO INT,
    FECHA DATE,
    CONSTRAINT PK_RECLAMO PRIMARY KEY (ID_RECLAMO),
    CONSTRAINT FK_RECLAMO_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(FOLIO)
);

CREATE TABLE COMENTARIOS (
    ID_COMENTARIO INT IDENTITY(1,1) NOT NULL,
	ID_RECLAMO INT NOT NULL,
    REMITENTE VARCHAR(10),
    FECHA DATETIME,
    DESCRIPCION VARCHAR(255),
    CONSTRAINT PK_COMENTARIOS PRIMARY KEY (ID_COMENTARIO),
    CONSTRAINT FK_COMENTARIOS_RECLAMO FOREIGN KEY (ID_RECLAMO) REFERENCES RECLAMO(ID_RECLAMO)
);
-- ======================
-- INSERTS DE EJEMPLO
-- ======================

-- JEFE
INSERT INTO JEFE (JEFE_ID, NOMBRE, VIGENTE, CONTRA, CORREO)
VALUES (1000, 'Carlos Gómez', 1, 'abcd', 'carlos@eddo.mx');

-- DOCENTE
INSERT INTO DOCENTE (ID_DOCENTE, NOMBRE, VIGENCIA, CONTRA, CORREO, TELEFONO)
VALUES (1, 'Ana Torres', 1, '123', 'ana.torres@tecnm.mx', '6671234567');

-- DEPARTAMENTO
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, JEFE_ID, NOMBRE)
VALUES (10, 1000, 'Ingeniería en Sistemas Computacionales');

-- CONVOCATORIA
INSERT INTO CONVOCATORIA (ID_CONVOCATORIA, NOMBRE, FECHA_INICIO, FECHA_FIN)
VALUES (200, 'Convocatoria 2025A', '2025-01-10', '2025-06-30');

-- EXPEDIENTE
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_DOCENTE, ID_CONVOC)
VALUES (300, 1, 200);

-- TIPO_DOCUMENTO
INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO, NOMBRE_DOCUMENTO)
VALUES 
(1, 'Currículum Vitae'),
(2, 'Constancia de Estudios'),
(3, 'Reconocimiento de Actividad');

-- TIPO_ACTIVIDAD
INSERT INTO TIPO_ACTIVIDAD (ID_TIPO_ACTIVIDAD, NOMBRE)
VALUES 
(1, 'Docencia'),
(2, 'Investigación');

-- ACTIVIDAD
INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, NOMBRE, DESCRIPCION, ID_TIPO_ACTIVIDAD)
VALUES 
(101, 'Curso de Programación Avanzada', 'Impartición de curso de programación en Java', 1),
(102, 'Proyecto de IA', 'Investigación sobre IA aplicada al deporte', 2);

-- DOCUMENTO (ahora con campo NOMBRE)
INSERT INTO DOCUMENTO (FOLIO, ID_TIPO_DOCUMENTO, ID_DEPARTAMENTO, ID_ACTIVIDAD, NOMBRE, APROBACION, FECHA)
VALUES 
(500, 1, 10, 101, 'CV Ana Torres', 1, '2025-03-15'),
(501, 3, 10, 102, 'Reconocimiento de Proyecto IA', 0, '2025-04-10');

-- DOCUMENTO_EXPEDIENTE (relación muchos a muchos)
INSERT INTO DOCUMENTO_EXPEDIENTE (ID_DOCUMENTO, ID_EXPEDIENTE)
VALUES 
(500, 300),
(501, 300);

-- RECLAMO
INSERT INTO RECLAMO (ID_RECLAMO, ID_DOCUMENTO, FECHA)
VALUES 
(700, 501, '2025-04-12');

-- COMENTARIOS
INSERT INTO COMENTARIOS (ID_RECLAMO, REMITENTE, FECHA, DESCRIPCION)
VALUES 
(700, 'DOCENTE', GETDATE(), 'El documento fue rechazado por error en formato.'),
(700, 'JEFE', GETDATE(), 'Favor de corregir el formato del archivo PDF.');

SELECT 
    DOC.NOMBRE AS NOMBRE_DOCUMENTO,
    DOC.APROBACION,
    DOC.FOLIO
FROM DOCUMENTO DOC
JOIN DOCUMENTO_EXPEDIENTE DE ON DOC.FOLIO = DE.ID_DOCUMENTO
JOIN EXPEDIENTE E ON DE.ID_EXPEDIENTE = E.ID_EXPEDIENTE
JOIN DOCENTE D ON E.ID_DOCENTE = D.ID_DOCENTE
JOIN CONVOCATORIA C ON E.ID_CONVOC = C.ID_CONVOCATORIA
JOIN DEPARTAMENTO DEP ON DOC.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
JOIN JEFE J ON DEP.JEFE_ID = J.JEFE_ID
JOIN TIPO_DOCUMENTO TD ON DOC.ID_TIPO_DOCUMENTO = TD.ID_TIPO_DOCUMENTO
JOIN RECLAMO R ON DOC.FOLIO = R.ID_DOCUMENTO
where D.ID_DOCENTE = 1

SELECT 
    DOC.NOMBRE AS NOMBRE_DOCUMENTO,
    DOC.APROBACION,
    DOC.FOLIO,
    CO.DESCRIPCION
FROM DOCUMENTO DOC
JOIN DOCUMENTO_EXPEDIENTE DE ON DOC.FOLIO = DE.ID_DOCUMENTO
JOIN EXPEDIENTE E ON DE.ID_EXPEDIENTE = E.ID_EXPEDIENTE
JOIN DOCENTE D ON E.ID_DOCENTE = D.ID_DOCENTE
JOIN CONVOCATORIA C ON E.ID_CONVOC = C.ID_CONVOCATORIA
JOIN DEPARTAMENTO DEP ON DOC.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
JOIN JEFE J ON DEP.JEFE_ID = J.JEFE_ID
JOIN TIPO_DOCUMENTO TD ON DOC.ID_TIPO_DOCUMENTO = TD.ID_TIPO_DOCUMENTO
JOIN RECLAMO R ON DOC.FOLIO = R.ID_DOCUMENTO
JOIN COMENTARIOS CO ON CO.ID_RECLAMO = R.ID_RECLAMO
WHERE (D.ID_DOCENTE = 1 AND DOC.NOMBRE like 'Reconocimiento de Proyecto IA') OR (J.JEFE_ID = 1 and  DOC.NOMBRE like 'Reconocimiento de Proyecto IA')
select * from COMENTARIOS c
join RECLAMO R ON c.ID_RECLAMO = R.ID_RECLAMO
SELECT * from RECLAMO
select * from DOCUMENTO_EXPEDIENTE
select * from DOCUMENTO
select * from EXPEDIENTE
SELECT 
    C.REMITENTE,
    C.FECHA AS FECHA_COMENTARIO,
    C.DESCRIPCION
FROM COMENTARIOS C
JOIN RECLAMO R ON C.ID_RECLAMO = R.ID_RECLAMO
JOIN DOCUMENTO D ON R.ID_DOCUMENTO = D.FOLIO
JOIN EXPEDIENTE E ON D.ID_EXPEDIENTE = E.ID_EXPEDIENTE
JOIN DOCENTE DOC ON E.ID_DOCENTE = DOC.ID_DOCENTE
JOIN DEPARTAMENTO DEP ON D.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
JOIN JEFE J ON DEP.JEFE_ID = J.JEFE_ID
WHERE (DOC.ID_DOCENTE = 1 AND DOC.NOMBRE = 501) OR (J.JEFE_ID = 1 and  DOC.NOMBRE = 501)
            SELECT * FROM RECLAMO
-- CHECKS Y DEFAULTS (ejemplo base, puedes ampliar)
ALTER TABLE DOCENTE ADD CONSTRAINT CHK_DOCENTE_VIGENTE CHECK (VIGENCIA IN (0,1));
ALTER TABLE JEFE ADD CONSTRAINT CHK_JEFE_VIGENTE CHECK (VIGENTE IN (0,1));
ALTER TABLE DOCUMENTO ADD CONSTRAINT CHK_DOCUMENTO_APROBACION CHECK (APROBACION IN (0,1));

ALTER TABLE DOCENTE ADD CONSTRAINT DF_DOCENTE_VIGENTE DEFAULT (1) FOR VIGENCIA;
ALTER TABLE JEFE ADD CONSTRAINT DF_JEFE_VIGENTE DEFAULT (1) FOR VIGENTE;
ALTER TABLE DOCUMENTO ADD CONSTRAINT DF_DOCUMENTO_APROBACION DEFAULT (0) FOR APROBACION;
