-- =====================================
-- CREACIÓN DE TABLAS (sin constraints)
-- =====================================
CREATE DATABASE EDDO;
USE EDDO
DROP DATABASE EDDO
CREATE TABLE DOCENTE (
    ID_DOCENTE INT NOT NULL,
    NOMBRE VARCHAR(100),
	VIGENCIA INT,
	CONTRA VARCHAR(20),
	CORREO VARCHAR(50),
    TELEFONO VARCHAR(15)
);
select * from DOCENTE
CREATE TABLE JEFE (
    JEFE_ID INT NOT NULL,
    NOMBRE VARCHAR(100),
    VIGENTE BIT,
	CONTRA VARCHAR(20),
	CORREO VARCHAR(50)
);

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT NOT NULL,
    JEFE_ID INT,
	NOMBRE VARCHAR(50)
);

CREATE TABLE CONVOCATORIA (
    ID_CONVOCATORIA INT NOT NULL,
    NOMBRE VARCHAR(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);

CREATE TABLE EXPEDIENTE (
    ID_EXPEDIENTE INT NOT NULL,
    ID_DOCENTE INT,
    ID_CONVOC INT
);

CREATE TABLE TIPO_DOCUMENTO (
    ID_TIPO_DOCUMENTO INT NOT NULL,
    NOMBRE_DOCUMENTO VARCHAR(100)
);

CREATE TABLE TIPO_ACTIVIDAD (
    ID_TIPO_ACTIVIDAD INT NOT NULL,
    NOMBRE VARCHAR(100)
);

CREATE TABLE ACTIVIDAD (
    ID_ACTIVIDAD INT NOT NULL,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(255),
    ID_TIPO_ACTIVIDAD INT
);

CREATE TABLE DOCUMENTO (
    FOLIO INT NOT NULL,
    ID_TIPO_DOCUMENTO INT,
    ID_EXPED INT,
    ID_DEPARTAMENTO INT,
    ID_ACTIVIDAD INT,
    APROBACION BIT,
    FECHA DATE
);

CREATE TABLE RECLAMO (
    ID_RECLAMO INT NOT NULL,
    ID_DOCUMENTO INT,
    FECHA DATE
);

CREATE TABLE COMENTARIOS (
    ID_COMENTARIO INT NOT NULL,
	ID_RECLAMO INT NOT NULL,
    DESCRIPCION VARCHAR(255)
);

-- =====================================
-- SECCIÓN DE CONSTRAINTS
-- =====================================

-- PRIMARY KEYS
ALTER TABLE DOCENTE ADD CONSTRAINT PK_DOCENTE PRIMARY KEY (ID_DOCENTE);
ALTER TABLE JEFE ADD CONSTRAINT PK_JEFE PRIMARY KEY (JEFE_ID);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID_DEPARTAMENTO);
ALTER TABLE CONVOCATORIA ADD CONSTRAINT PK_CONVOCATORIA PRIMARY KEY (ID_CONVOCATORIA);
ALTER TABLE EXPEDIENTE ADD CONSTRAINT PK_EXPEDIENTE PRIMARY KEY (ID_EXPEDIENTE);
ALTER TABLE TIPO_DOCUMENTO ADD CONSTRAINT PK_TIPO_DOCUMENTO PRIMARY KEY (ID_TIPO_DOCUMENTO);
ALTER TABLE TIPO_ACTIVIDAD ADD CONSTRAINT PK_TIPO_ACTIVIDAD PRIMARY KEY (ID_TIPO_ACTIVIDAD);
ALTER TABLE ACTIVIDAD ADD CONSTRAINT PK_ACTIVIDAD PRIMARY KEY (ID_ACTIVIDAD);
ALTER TABLE DOCUMENTO ADD CONSTRAINT PK_DOCUMENTO PRIMARY KEY (FOLIO);
ALTER TABLE RECLAMO ADD CONSTRAINT PK_RECLAMO PRIMARY KEY (ID_RECLAMO);
ALTER TABLE COMENTARIOS ADD CONSTRAINT PK_COMENTARIOS PRIMARY KEY (ID_COMENTARIO);

-- FOREIGN KEYS
ALTER TABLE DEPARTAMENTO 
ADD CONSTRAINT FK_DEP_JEFE_ID FOREIGN KEY (JEFE_ID) 
REFERENCES JEFE(JEFE_ID);

ALTER TABLE EXPEDIENTE 
ADD CONSTRAINT FK_EXPEDIENTE_DOCENTE FOREIGN KEY (ID_DOCENTE) 
REFERENCES DOCENTE(ID_DOCENTE);

ALTER TABLE EXPEDIENTE 
ADD CONSTRAINT FK_EXPEDIENTE_CONVOC FOREIGN KEY (ID_CONVOC) 
REFERENCES CONVOCATORIA(ID_CONVOCATORIA);

ALTER TABLE ACTIVIDAD 
ADD CONSTRAINT FK_ACTIVIDAD_TIPO_ACT FOREIGN KEY (ID_TIPO_ACTIVIDAD)
REFERENCES TIPO_ACTIVIDAD(ID_TIPO_ACTIVIDAD);

ALTER TABLE DOCUMENTO 
ADD CONSTRAINT FK_DOCUMENTO_TIPO_DOC FOREIGN KEY (ID_TIPO_DOCUMENTO)
REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO);

ALTER TABLE DOCUMENTO 
ADD CONSTRAINT FK_DOCUMENTO_EXPED FOREIGN KEY (ID_EXPED)
REFERENCES EXPEDIENTE(ID_EXPEDIENTE);

ALTER TABLE DOCUMENTO 
ADD CONSTRAINT FK_DOCUMENTO_DEP FOREIGN KEY (ID_DEPARTAMENTO)
REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO);

ALTER TABLE DOCUMENTO 
ADD CONSTRAINT FK_DOCUMENTO_ACT FOREIGN KEY (ID_ACTIVIDAD)
REFERENCES ACTIVIDAD(ID_ACTIVIDAD);

ALTER TABLE RECLAMO 
ADD CONSTRAINT FK_RECLAMO_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO)
REFERENCES DOCUMENTO(FOLIO);

ALTER TABLE COMENTARIOS 
ADD CONSTRAINT FK_COMENTARIOS_RECLAMO FOREIGN KEY (ID_RECLAMO)
REFERENCES RECLAMO(ID_RECLAMO)


-- CHECKS Y DEFAULTS (ejemplo base, puedes ampliar)
ALTER TABLE DOCENTE ADD CONSTRAINT CHK_DOCENTE_VIGENTE CHECK (VIGENCIA IN (0,1));
ALTER TABLE JEFE ADD CONSTRAINT CHK_JEFE_VIGENTE CHECK (VIGENTE IN (0,1));
ALTER TABLE DOCUMENTO ADD CONSTRAINT CHK_DOCUMENTO_APROBACION CHECK (APROBACION IN (0,1));

ALTER TABLE DOCENTE ADD CONSTRAINT DF_DOCENTE_VIGENTE DEFAULT (1) FOR VIGENCIA;
ALTER TABLE JEFE ADD CONSTRAINT DF_JEFE_VIGENTE DEFAULT (1) FOR VIGENTE;
ALTER TABLE DOCUMENTO ADD CONSTRAINT DF_DOCUMENTO_APROBACION DEFAULT (0) FOR APROBACION;
